//! Cross-implementation differential test against `rust-hpke` (rozbb/hpke).
//!
//! `tests/differential.rs` compares against `hpke-rs`, whose RustCrypto backend
//! supports only X25519, P-256 and secp256k1. This file covers the KEMs that
//! had no independent validation at all — P-384, ML-KEM-768, ML-KEM-1024 and
//! X-Wing — plus X25519 and P-256 as controls proving the harness itself is
//! sound, and P-521 which previously had KAT coverage but no cross-check.
//!
//! Unlike the `hpke-rs` harness this needs no `hazmat-` feature: it drives both
//! libraries entirely through their public APIs. Each suite runs both
//! directions — hpke-ng seals and rust-hpke opens, then rust-hpke seals and
//! hpke-ng opens — and the two exporter secrets must agree. Between them those
//! checks pin the public-key, private-key and encapsulated-key wire formats,
//! `kem_context` construction, the key schedule, the AEAD nonce sequence, and
//! the exporter.

#![allow(non_snake_case)]

use hpke::{
	Deserializable, Kem as RhKem, OpModeR, OpModeS, Serializable, setup_receiver,
	setup_sender_with_rng,
};
use hpke_ng as ng;
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha20Rng;

const ITERATIONS: usize = 3;

/// Full bidirectional interop for one ciphersuite.
///
/// Keys are generated by hpke-ng and handed to rust-hpke as wire bytes, which
/// also asserts that both libraries serialize them identically. That works for
/// every KEM regardless of how each side implements `DeriveKeyPair`.
macro_rules! diff_rh {
	(
		$name:ident,
		$ng_kem:ty, $ng_kdf:ty, $ng_aead:ty,
		$rh_kem:ty, $rh_kdf:ty, $rh_aead:ty,
		$seed:expr
	) => {
		#[test]
		fn $name() {
			type NgSuite = ng::Hpke<$ng_kem, $ng_kdf, $ng_aead>;
			type RhPublicKey = <$rh_kem as RhKem>::PublicKey;
			type RhPrivateKey = <$rh_kem as RhKem>::PrivateKey;
			type RhEncappedKey = <$rh_kem as RhKem>::EncappedKey;

			let mut prng = ChaCha20Rng::seed_from_u64($seed);

			for iter in 0..ITERATIONS {
				let mut buf = |n: usize| {
					let mut v = vec![0u8; n];
					prng.fill_bytes(&mut v);
					v
				};
				let info = buf(16);
				let aad = buf(16);
				let pt = buf(64);

				// --- Keys: generated by hpke-ng, loaded by rust-hpke ---------
				let (ng_sk, ng_pk) = <$ng_kem as ng::Kem>::generate(&mut prng).unwrap();
				let pk_bytes = ng_pk.as_ref().to_vec();
				let sk_bytes = <$ng_kem as ng::Kem>::sk_to_bytes(&ng_sk);

				let rh_pk = RhPublicKey::from_bytes(&pk_bytes)
					.expect("rust-hpke rejected an hpke-ng public key");
				let rh_sk = RhPrivateKey::from_bytes(&sk_bytes)
					.expect("rust-hpke rejected an hpke-ng private key");
				assert_eq!(
					&rh_pk.to_bytes()[..],
					pk_bytes.as_slice(),
					"public key serialization diverged (iter {iter})",
				);
				assert_eq!(
					&rh_sk.to_bytes()[..],
					sk_bytes.as_slice(),
					"private key serialization diverged (iter {iter})",
				);

				// --- Direction A: hpke-ng seals, rust-hpke opens -------------
				let (ng_enc, ng_ct) =
					NgSuite::seal_base(&mut prng, &ng_pk, &info, &aad, &pt).unwrap();
				let rh_enc = RhEncappedKey::from_bytes(ng_enc.as_ref())
					.expect("rust-hpke rejected an hpke-ng encapsulated key");
				let mut rh_recv = setup_receiver::<$rh_aead, $rh_kdf, $rh_kem>(
					&OpModeR::Base,
					&rh_sk,
					&rh_enc,
					&info,
				)
				.expect("rust-hpke setup_receiver");
				assert_eq!(
					rh_recv
						.open(&ng_ct, &aad)
						.expect("rust-hpke could not open"),
					pt,
					"rust-hpke open of hpke-ng ciphertext (iter {iter})",
				);

				// --- Direction B: rust-hpke seals, hpke-ng opens -------------
				let (rh_enc2, mut rh_send) = setup_sender_with_rng::<$rh_aead, $rh_kdf, $rh_kem>(
					&OpModeS::Base,
					&rh_pk,
					&info,
					&mut prng,
				)
				.expect("rust-hpke setup_sender");
				let rh_ct = rh_send.seal(&pt, &aad).expect("rust-hpke seal");

				let ng_enc2 = <$ng_kem as ng::Kem>::enc_from_bytes(&rh_enc2.to_bytes()[..])
					.expect("hpke-ng rejected a rust-hpke encapsulated key");
				assert_eq!(
					NgSuite::open_base(&ng_enc2, &ng_sk, &info, &aad, &rh_ct)
						.expect("hpke-ng could not open"),
					pt,
					"hpke-ng open of rust-hpke ciphertext (iter {iter})",
				);

				// --- Exporter agreement on the shared context ----------------
				// Sender and receiver derive the same exporter secret, so the
				// rust-hpke sender context and the hpke-ng receiver context
				// must export identical values.
				let ng_recv = NgSuite::setup_receiver_base(&ng_enc2, &ng_sk, &info).unwrap();
				for &l in &[16usize, 32, 64] {
					let mut rh_out = vec![0u8; l];
					rh_send
						.export(b"diff-export", &mut rh_out)
						.expect("rust-hpke export");
					assert_eq!(
						ng_recv.export(b"diff-export", l).unwrap(),
						rh_out,
						"export len={l} diverged (iter {iter})",
					);
				}
			}
		}
	};
}

// Controls: suites already covered against `hpke-rs`. If these fail, the
// harness is wrong rather than the KEM under test.
diff_rh!(
	rh_x25519_sha256_chacha20,
	ng::DhKemX25519HkdfSha256,
	ng::HkdfSha256,
	ng::ChaCha20Poly1305,
	hpke::kem::X25519HkdfSha256,
	hpke::kdf::HkdfSha256,
	hpke::aead::ChaCha20Poly1305,
	0x0000_1111
);
diff_rh!(
	rh_p256_sha256_aes128,
	ng::DhKemP256HkdfSha256,
	ng::HkdfSha256,
	ng::Aes128Gcm,
	hpke::kem::DhP256HkdfSha256,
	hpke::kdf::HkdfSha256,
	hpke::aead::AesGcm128,
	0x0000_2222
);

// P-384: no RFC 9180 vectors are bundled and `hpke-rs` cannot do it, so this is
// its only independent validation.
diff_rh!(
	rh_p384_sha384_aes256,
	ng::DhKemP384HkdfSha384,
	ng::HkdfSha384,
	ng::Aes256Gcm,
	hpke::kem::DhP384HkdfSha384,
	hpke::kdf::HkdfSha384,
	hpke::aead::AesGcm256,
	0x0000_3333
);
diff_rh!(
	rh_p521_sha512_aes256,
	ng::DhKemP521HkdfSha512,
	ng::HkdfSha512,
	ng::Aes256Gcm,
	hpke::kem::DhP521HkdfSha512,
	hpke::kdf::HkdfSha512,
	hpke::aead::AesGcm256,
	0x0000_4444
);

// Post-quantum KEMs: no published RFC 9180 vectors exist, and `hpke-rs`'s
// RustCrypto backend has no PQ support, so this is their only cross-check.
#[cfg(feature = "pq")]
mod pq {
	use super::*;

	diff_rh!(
		rh_mlkem768_sha256_chacha20,
		ng::MlKem768,
		ng::HkdfSha256,
		ng::ChaCha20Poly1305,
		hpke::kem::MlKem768,
		hpke::kdf::HkdfSha256,
		hpke::aead::ChaCha20Poly1305,
		0x0000_5555
	);
	diff_rh!(
		rh_mlkem1024_sha256_aes256,
		ng::MlKem1024,
		ng::HkdfSha256,
		ng::Aes256Gcm,
		hpke::kem::MlKem1024,
		hpke::kdf::HkdfSha256,
		hpke::aead::AesGcm256,
		0x0000_6666
	);
	diff_rh!(
		rh_xwing_sha256_chacha20,
		ng::XWingDraft06,
		ng::HkdfSha256,
		ng::ChaCha20Poly1305,
		hpke::kem::XWing,
		hpke::kdf::HkdfSha256,
		hpke::aead::ChaCha20Poly1305,
		0x0000_7777
	);
}

// ---------------------------------------------------------------------------
// `DeriveKeyPair` agreement.
//
// Two conformant implementations must produce identical key pairs from the same
// IKM: RFC 9180 §7.1.3 fixes it for the DHKEMs, and draft-ietf-hpke-pq §3.2/§4.2
// fixes it for ML-KEM and the hybrids via
// `SHAKE256.LabeledDerive(ikm, "DeriveKeyPair", "", Nsk)`.
//
// The PQ rows are the only check that hpke-ng's `LabeledDerive` byte layout
// (draft-ietf-hpke-hpke §4: `ikm || "HPKE-v1" || suite_id ||
// lengthPrefixed(label) || I2OSP(L, 2) || context`) is right — no published
// DeriveKeyPair vectors exist for these KEMs, so agreement with an independent
// implementation is the available oracle. `tests/kat_xwing.rs` pins the X-Wing
// primitive itself against the draft's own vectors.
// ---------------------------------------------------------------------------

macro_rules! diff_rh_derive_key_pair {
	($name:ident, $ng_kem:ty, $rh_kem:ty, $seed:expr) => {
		#[test]
		fn $name() {
			let mut prng = ChaCha20Rng::seed_from_u64($seed);
			for iter in 0..ITERATIONS {
				// 64 bytes is safe for every Nsk here (P-521 needs 66 bits of
				// rejection sampling input but accepts any IKM length).
				let mut ikm = vec![0u8; 64];
				prng.fill_bytes(&mut ikm);

				let (_, ng_pk) = <$ng_kem as ng::Kem>::derive_key_pair(&ikm).unwrap();
				let (_, rh_pk) = <$rh_kem as RhKem>::derive_keypair(&ikm);
				assert_eq!(
					ng_pk.as_ref(),
					&rh_pk.to_bytes()[..],
					"DeriveKeyPair diverged (iter {iter})",
				);
			}
		}
	};
}

diff_rh_derive_key_pair!(
	rh_dkp_x25519,
	ng::DhKemX25519HkdfSha256,
	hpke::kem::X25519HkdfSha256,
	0x000A_AAAA
);
diff_rh_derive_key_pair!(
	rh_dkp_p256,
	ng::DhKemP256HkdfSha256,
	hpke::kem::DhP256HkdfSha256,
	0x000B_BBBB
);
diff_rh_derive_key_pair!(
	rh_dkp_p384,
	ng::DhKemP384HkdfSha384,
	hpke::kem::DhP384HkdfSha384,
	0x000C_CCCC
);
diff_rh_derive_key_pair!(
	rh_dkp_p521,
	ng::DhKemP521HkdfSha512,
	hpke::kem::DhP521HkdfSha512,
	0x000D_DDDD
);

#[cfg(feature = "pq")]
mod pq_dkp {
	use super::*;

	diff_rh_derive_key_pair!(
		rh_dkp_mlkem768,
		ng::MlKem768,
		hpke::kem::MlKem768,
		0x000E_EEEE
	);
	diff_rh_derive_key_pair!(
		rh_dkp_mlkem1024,
		ng::MlKem1024,
		hpke::kem::MlKem1024,
		0x000F_FFFF
	);
	diff_rh_derive_key_pair!(
		rh_dkp_xwing,
		ng::XWingDraft06,
		hpke::kem::XWing,
		0x0011_1111
	);
}
